version: '3.1'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: containerMarket
volumes:
  database:
