spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3300/containerMarket
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
